name: min_max_heap
description: A MinMax binary heap data structure implementation.
version: 1.0.0
repository: https://github.com/ElanDeyan/min_max_heap_dart

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
# dependencies:


dev_dependencies:
  lint: ^2.1.2
  lints: ^2.0.0
  test: ^1.21.0
