name: min_max_heap
description:
  A Min-max binary heap data structure implementation. AKA double ended priority queue. Supports generics.
version: 2.1.0
repository: https://github.com/ElanDeyan/min_max_heap_dart

topics: 
  - data-structures
  - priority

environment:
  sdk: ^3.0.5

dependencies:
  logging: ^1.2.0

dev_dependencies:
  lint: ^2.1.2
  lints: ^2.0.0
  test: ^1.21.0
